FROM rocker/r-ver:4

RUN apt update && apt upgrade -y \
    && apt install -y libfontconfig1-dev \
    libharfbuzz-dev libfribidi-dev \
    libcurl4-openssl-dev libxml2-dev \
    libfreetype6-dev libpng-dev libtiff5-dev \ 
    libjpeg-dev libssl-dev libglpk40 xdg-utils --fix-missing \
    && R -e "install.packages(c('digest', 'devtools'))" \
    && R -e "devtools::install_github('gsx-ucas/QRAP', upgrade = 'always')"

WORKDIR /home/QRAP_WD
EXPOSE 3030 3838 3939 

CMD R -e "QRAP::startQRAP(port = 3838)"
