---
title: "Untitled"
author: "Shixue Gou"
date: "2021/1/26"
output: html_document
---

```{r}
library(pathview)
```

```{r}
data(gse16873.d)
data(demo.paths)
i <- 1

pv.out <- pathview(gene.data = gse16873.d[, 1], pathway.id = demo.paths$sel.paths[i],species = "hsa", out.suffix = "gse16873.2layer", kegg.native = F)

pv.out <- pathview(gene.data = gse16873.d[, 1], pathway.id = demo.paths$sel.paths[i], species = "hsa", out.suffix = "gse16873", kegg.native = F, pdf.size = c(10, 10), cex = 0.7, key.pos ="topright", sign.pos = "topright", limit = list(gene = 3), bins = list(gene = 10))
```

```{r}
pv.out <- pathview(gene.data = gse16873.d[, 1], pathway.id = demo.paths$sel.paths[i], species = "hsa", out.suffix = "gse16873.2layer", kegg.native = F, sign.pos = demo.paths$spos[i], same.layer = T, split.group = T, expand.node = T)
```

```{r}
ko.data=sim.mol.data(mol.type="gene.ko", nmol=5000)
pv.out <- pathview(gene.data = ko.data, pathway.id = "04112", species = "ko", out.suffix = "ko.data", kegg.native = T)
```

```{r}
library(dplyr)
degs <- read.csv("~/Desktop/APP_Test/GSE147507_Human_patients/DEGs/COVID19Lung_vs_HealthyLungBiopsy.csv", row.names = 1)
degs <- degs %>% tibble::rownames_to_column(var = "input") 
convert_df <- gprofiler2::gconvert(degs$input, organism = "mesculenta", target = "INTENZ")

# joined_df <- left_join(degs, convert_df, by = "input") %>% filter(target != "nan")
convert_df

```

```{r}
input <- degs$log2FoldChange
names(input) <- degs$input
pv.out <- pathview(gene.data = input, pathway.id = "oaa03020", species = "oaa", gene.idtype = "SYMBOL", out.suffix = "gse16873", kegg.native = F, pdf.size = c(10, 10), cex = 0.7, key.pos ="topright", sign.pos = "topright", limit = list(gene = 3), bins = list(gene = 10))
```

```{r}
data(bods); bods
data(gene.idtype.list); gene.idtype.list

gene.idtype.list[1]
```

